#!/bin/bash

cd Generators

python constraint_generator.py
python decoder_generator.py
python modify_generator.py
python qed_generator.py

cd ..

# TO BE REMOVED: copy fixed QED files from 'QEDFiles-bug-fix' to
# 'QEDFiles'. These files will be generated by the fixed workflow.
cp QEDFiles-bug-fix/* QEDFiles/
